export const CONTRACT_IDS = {
  access_control: "CCWAOZBNW2KCSI4HQYKHX3LVOBJR7GKUXLLG245ASZ3HSAQ4VJOBNXXD",
  audit_trail: "CDGSVMBRFJP4S76INYCXZAMO7MCFW56MJ635AVR43P25WYSGVXSF4PL5",
  community_oracle: "CA6WW77NRF6OYFHMMYBMZFP35C335L2PFGTOG3VYRV56ZMM6S62BLWPY",
  escrow: "CAHCHIL67KRPP4TGCU7ODKU3PKLYFMSWR3FQYM3JETKJKA4DAAFSLJJQ",
  pvo_core: "CDE45UWFGGCQLKW42AGEU23ATCUKYH64J4ILXWHKBNQANQMY7STPIYND",
  reputation: "CC3KD33I5TZ3VPCNBVK5PYSTDDAXSZ6HQJWQ4ZSE5B2N5HQL22ZDQHJ3",
  value_score: "CCPRWGHWYIG77M7IBNC7PK7SYQE65ESH5NMLRSQDKY4T3XLXIGCZUDPU",
  ai_oracle: "CBPG66PB5D2SMQSYF2OWFJ2LZGJEQHJWC6CBAIKEO42DLOLCMIIO7QFA",
  public_index: "CBGL743HYP4HSW2LPC645CWYESEYPYTZAAP4TZLJXNKLDAGU6Y5XQZ3Q",
  compliance_engine: "CABYLCRNGBUF73FYH24MKI5JDJPGLAIEAVEHX7OC2B2U25QQLF3KYRJW",
  procurement_market: "CBB6JO3ZIDGUVLPJ4C75DHXKT6HABHUJLALSIYLQKFNMBKNFQIBXPBE7",
  pphp: "CCJRBA36WHKFDUJMNW2BPP7OYHNUJHJ4MYAQW4ORCTF2IEIOWW5ZA32X",
  pphp_sac: "CCJRBA36WHKFDUJMNW2BPP7OYHNUJHJ4MYAQW4ORCTF2IEIOWW5ZA32X",
  grant_commitment: "CACKV7KP2FNO5FGX6SNXTUNGUBWCAOMVRUOLPWEAGRA7X2SQV4RWKKMQ",
} as const;

export const NETWORK_PASSPHRASE = "Test SDF Network ; September 2015";
export const RPC_URL = "https://soroban-testnet.stellar.org:443";
export const NETWORK = "testnet";

export const RPT_ASSET = "CCZCWNF4N7ZAZT4GWEWNW44LIOAEWILB56GUIA6BJZ3BYJKTHTEJFCAQ";
export const RPT_MIN_BALANCE = 1;
export const CURRENCIES = ["₱", "$", "€", "£", "¥", "₿"] as const;
export const FUNDING_AGENCY = "GBM5YDPFH5NI7IRLHYFGLBAAIZGBOO5WGQQRNG3YWLTLHVF7GVJZ5PBO";
export const PPHP_SCALE = 10_000_000;

export function getCurrency(): string {
  try { return localStorage.getItem("popv_currency") || "₱"; } catch { return "₱"; }
}
export function setCurrency(sym: string): void {
  try { localStorage.setItem("popv_currency", sym); } catch {}
}
