export const CONTRACT_IDS = {
  access_control: "CCAOA7UZDDRVB3Y6RPV5RZXWXODREUSNDDZQLD3EI2KZVGAJIGG4WWMN",
  audit_trail: "CBQPQ5ISUYF37RM23G4UJB3RAEAT2F74PZHLNW7ZVCGAGEXZFL2E4LTO",
  community_oracle: "CDNCNRELOGMIK23PWHLOFHG25NFIUJBV32AJRC5WJNFHMRSTRIQWOABA",
  escrow: "CDS6QJB5TLDPTXDJF3WABEY3CT73P2MFRTO7UEB2SL7EUTZKT4QJLR6M",
  pvo_core: "CCWMZE527DTPNR4KVKTJMOUQ6A4ITKXNNO2NFDEVESMGCXZVWD6AZGE4",
  reputation: "CDWMWDIVX5I2C2XH42WVEVA5JXW6HAWYRRLWSMYZHTO3OMEJRZ6EVVLU",
  value_score: "CA3EADWOQZ4RLJUHP2KFNBOVZ7XGJQKJOGST4X5P2DZ6B3KGFQK27BOJ",
  ai_oracle: "CAVD64WSZLOVV35RFKPG2OFVRCR3F3LGXQYSFR2JTDSGIBYKBXKUBP25",
  public_index: "CC4LG7NYMR4ZCNNTMFL42RECG4FXP67DKCRXR2MA53LM3PDUK6KQVULC",
  compliance_engine: "CBUKSKFM26BMIMC7H7SSJ2A4LUDX5IREANPWCHWR54R5T7BDHUUCWPBH",
  procurement_market: "CBKTM7F32KJJWVGYRCNNJQNXK5DHEISJMFESXAAJJYDSDSJYMRKJSHUW",
  pphp: "CANQ5IHIQQIXSWU3LT534HUBJBKCSLL3FPU2NW6WA2MMN2D5Y5DKWA2Y",
  pphp_sac: "CCJRBA36WHKFDUJMNW2BPP7OYHNUJHJ4MYAQW4ORCTF2IEIOWW5ZA32X",
  grant_commitment: "CDTJ5YY4VX6UA6YMKSSPDLIUXKXENUV6JYKMOBM6762XTBGGNQXFFWRK",
} as const;

export const NETWORK_PASSPHRASE = "Test SDF Network ; September 2015";
export const RPC_URL = "https://soroban-testnet.stellar.org:443";
export const NETWORK = "testnet";

export const RPT_ASSET = "CCZCWNF4N7ZAZT4GWEWNW44LIOAEWILB56GUIA6BJZ3BYJKTHTEJFCAQ";
export const RPT_MIN_BALANCE = 1;

export const CURRENCIES = ["₱", "$", "€", "£", "¥", "₿"] as const;

export const FUNDING_AGENCY = "GBM5YDPFH5NI7IRLHYFGLBAAIZGBOO5WGQQRNG3YWLTLHVF7GVJZ5PBO";

export function getCurrency(): string {
  try { return localStorage.getItem("popv_currency") || "₱"; } catch { return "₱"; }
}

export function setCurrency(sym: string): void {
  try { localStorage.setItem("popv_currency", sym); } catch {}
}
