export const CONTRACT_IDS = {
  access_control: "CBDWHDIO637P7XCYEQMO52LMJBNOJYSALCWSGUJ2RQKRRDDME34MA746",
  audit_trail: "CCFCRX5MICL3NG56QNF7MQHXVGQJIDTUIXZN6KGGZIMXEGCCK4Z5C6YZ",
  community_oracle: "CCDHOEMHNVIC43J6VXORC4JUYPFXKQXSOSBSVKDJKTLOG5R6O6FV5T3H",
  escrow: "CCPFTZZBYWEP2LMQR5I2LT46NSPQ6WHLR4N4MP6JN66GUH2KKYD23DFA",
  pvo_core: "CBMPRCK3OOQZNOSNLHWVU3RS5NHR4YCALTTVWFDGVIPE2PTL376I4XYK",
  reputation: "CCHXNWKY75BKES332KASOFWD6WLFSQU2GWPYTOH2U4H7AGVDQB2WWWIB",
  value_score: "CBR3TNBTULT6UYAPCC6PZMAU2EWRO737VZLHICARMBAIQILJQRFTQ5BD",
  ai_oracle: "CBCL4WYFXHRMDMP2BBLCGWXTJGMT6V25MIULRIPEWREXDTX4NYODECSQ",
  public_index: "CCHK2SV6OZSO45KHTIUA2SAXAO4W47VNBJ3SGMRGND5GZ5LT2ST7XYZT",
  compliance_engine: "CD5ZAPMO7VCCJICL5BMRXADEOH435RDVKIHHFOXOLTOGF3OCXOJKE7FQ",
  procurement_market: "CCEB5AHLB7ZIRXMDPPOTAHP47W5FNADETU63VEVYN4QSF4QXTSLDFCXP",
  pphp: "CCJRBA36WHKFDUJMNW2BPP7OYHNUJHJ4MYAQW4ORCTF2IEIOWW5ZA32X",
  pphp_sac: "CCJRBA36WHKFDUJMNW2BPP7OYHNUJHJ4MYAQW4ORCTF2IEIOWW5ZA32X",
  grant_commitment: "CC5BHN236NBYKIUOXWZINJSOXUXCQBXZETRMOBLQMMXOFMPG5KHN6CJZ",
} as const;

export const NETWORK_PASSPHRASE = "Test SDF Network ; September 2015";
export const RPC_URL = "https://soroban-testnet.stellar.org:443";
export const NETWORK = "testnet";

export const RPT_ASSET = "CCZCWNF4N7ZAZT4GWEWNW44LIOAEWILB56GUIA6BJZ3BYJKTHTEJFCAQ";
export const RPT_MIN_BALANCE = 1;
export const CURRENCIES = ["₱", "$", "€", "£", "¥", "₿"] as const;
export const FUNDING_AGENCY = "GBM5YDPFH5NI7IRLHYFGLBAAIZGBOO5WGQQRNG3YWLTLHVF7GVJZ5PBO";
export const PPHP_SCALE = 10_000_000;

export function getCurrency(): string {
  try { return localStorage.getItem("popv_currency") || "₱"; } catch { return "₱"; }
}
export function setCurrency(sym: string): void {
  try { localStorage.setItem("popv_currency", sym); } catch {}
}
